baseURL = "https://binarize.io"
languageCode = "en-us"
theme = "simple-html"
title = "binarize.io"
name = "binarize.io"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "about"
    name = "#About"
    url = "/about"
